### ISSUE TITLE
ToDo Liste

### ISSUE THREAD

**Issue by nevrome** [RR104/royal-rangers-kiel.de#1]
Anstatt einzelner Issues habe ich mich entschieden, die wesentlichen ToDos in einer Liste zusammen zu stellen.

- Layout/Design
  - [x] Farbschema bestimmen und Reihenfolge festlegen
  - [x] Bannerfoto auswählen (Banner darf ruhig doppelt so hoch sein, wie das aktuelle), für das wir die notwendigen Nutzungsrechte haben
  - [ ] Allgemeine Aufwertung
  - [x] Titelbug beheben (Titel rutscht bei kleiner Fensterbreite aus dem Banner)
- Inhalt
  - [ ] Willkommenstext + Kontaktmöglichkeiten nach Vorlage des Textes von der alten HP zusammenstellen
  - [ ] Impressumstext zusammenstellen
  - [x] Team+Leiter-Liste erstellen - eine sinnvoll strukturierte, leicht zu überarbeitende .csv Datei
- Webprogramming
  - [x] Automatisch aus der Team+Leiter-Liste generierte Team+Leiter-Kacheln (siehe #2)
  - [x] Termin+News-Applet, nach Möglichkeit mit Verbindung zu Christophs Kalender (wenn API vorhanden), ansonsten über .csv Datei

@kirillkiel @ChristBoe
